### ISSUE TITLE
utils의 array 관련 함수를 조금 더 간소하게 작성할 수 있을듯 합니다

### ISSUE THREAD

**Issue by Danue1** [ridi/library-frontend#95]
# 개요

지금의 코드도 작동하는 것에는 문제가 없지만, 조금 더 정리하면 간소하게 정리할 수 있습니다.

```typescript
// before
export const splitArrayByChunk = (array, chunkSize) =>
  Array(Math.ceil(array.length / chunkSize))
    .fill()
    .map((_, index) => index * chunkSize)
    .map(begin => array.slice(begin, begin + chunkSize));

// after
export const splitArrayByChunk = (array, chunkSize) =>
  Array.from({ length: Math.ceil(array.length / chunkSize) }, (_, index) => {
    const begin = index * chunkSize;
    return array.slice(begin, begin + chunkSize);
  });
```

대표적으로 splitArrayByChunk는 Array.from 메서드로 재작성할 수 있고,
이렇게 재작성하는 경우 O(3 * n)에서 O(n)으로 줄일 수 있습니다.

# 참조

이 이슈는 시간상 아래의 PR로부터 시작합니다.

https://github.com/ridi/library-frontend/pull/53

p.s. 늦었습니다. 민폐를 끼쳐 죄송합니다...

**Comment by namenu** [comment]
@Danue1 타당한 지적이고 친절히 보내주신 PR도 유효했는데 확인이 늦어졌습니다.
현재 PR은 닫혀서 내용을 확인할 수 없지만, 추후 관련한 수정이 발생하게 된다면 안내드리도록 하겠습니다.

관심 주셔서 진심으로 감사드립니다!
